### ISSUE TITLE
Add tests for column presence and format to the pipeline tests

### ISSUE THREAD

**Issue by StefanVriend** [SPI-Birds/pipelines#143]
The format of the 4 tables is currently checked as part of the quality check. However, it would be more appropriate if this is moved to the tests, so that pipeline testing and data checking are fully separated.

Tests should test the following things (also see #140):

- Is the class of each column as expected in the standard format?
- Is each variable in the standard format present?
- Are there any redundant variables present?

This means that the "internal" checks B1, C1, I1 and L1 will be removed.

**Comment by ChloeRN** [comment]
Made a start on testing for presence and order of columns (in #152)  but it fails when applied to the output of `run_pipelines`, because that output is currently a mix of v1.0 and v1.1 standard format and contains non-standard columns (see Issue #140 ). 
We will have to fix issue #140 and then find a creative way to let this work in the presence of multiple standard format versions.

**Comment by StefanVriend** [comment]
Good to know, thanks! When I work on the formatting check and old pipeline updates I will first look at #140.
