### ISSUE TITLE
Check that all adults captured on a nest are listed as being parents of that nest

### ISSUE THREAD

**Issue by LiamDBailey** [SPI-Birds/pipelines#37]
In Capture_data, find all individuals that were captured with Age_calculated > 3 and where LocationID is classified as Location_type "NB" in the Location_data table (i.e. find all cases of adults that were captured on nest boxes).

Then, for each individual, check that it was listed as one of the parents of that nest on which it was caught.

**Comment by StefanVriend** [comment]
I think I have worked out the code for this check:

1. Select adults from Capture_data.
2. Link adults to Location_data to obtain location type of their captures.
3. Select adults caught on nest boxes.
4. Link adults to Brood_data to check whether they are listed as parents of the nest they are captured on.

However, what do you, @LiamDBailey and @ChloeRN, think about violations of this check - should those result in an error or a warning? On the one hand, I think it should be a warning, because individuals are perhaps caught _near_ the nest rather than _on_ the nest. On the other hand, I think it could be an error, because there might be cases where wrong parents are associated to nests and this is (perhaps) the (only) way to find that out?

**Comment by ChloeRN** [comment]
@StefanVriend, intuitively I would say that this should result in a warning, not an error. As you say, non-parent individuals may be caught very close to the nest (such that the data owners still gave the nest as the location). I have also heard that sometimes non-parents are caught IN the boxes as well. So that seems to be something that does happen occasionally. 

The potential risk of data-owners having assigned wrong parents to the nest (either by capturing a non-parent, or by typo in the data), seems to me to be the lesser evil than flagging all non-parent captures on nests as errors. 

What do you think, @LiamDBailey ?

**Comment by StefanVriend** [comment]
Note: This problem can be fixed if we add a column CaptureType to Capture_data (see #72).

**Comment by LiamDBailey** [comment]
I agree, keeping this as a warning makes the most sense to me. I think there is too much uncertainty in the actually location of capture to confidently say that this could be an error. For example, in some cases a capture at a nest box could be a capture in a mist net in front of a nest box. It's often impossible for us to distinguish these unless it's explicitly listed in the data.
